import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { NavBar } from "./components/navbar";
import { Cards } from "./components/cards";
import { SessionProvider } from "next-auth/react";
import { NextAuthProvider } from "@/next-auth/nextAuthProviders";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <NextAuthProvider>
                    <Providers>
                        <Toaster position="top-right" reverseOrder={true} />

                        <NavBar />
                        {children}
                    </Providers>
                </NextAuthProvider>
            </body>
        </html>
    );
}
