import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { NavBar } from "./components/navbar";
import { Cards } from "./components/cards";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    <div className="min-h-screen bg-gray-100">
                        <NavBar />
                        {children}
                    </div>
                </Providers>
            </body>
        </html>
    );
}
